version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    # The database connection is configured via DATABASE_URL in the .env file
    # which should point to your remote database server

volumes:
  postgres_data: 